#ifndef _NXP_SIMTEMP_IOCTL_H_
#define _NXP_SIMTEMP_IOCTL_H_

#include <linux/ioctl.h>
#include <linux/types.h>

#define NXP_SIMTEMP_MAGIC 'T'
#define SIMTEMP_GET_STATUS _IOR(NXP_SIMTEMP_MAGIC, 2, __u32)
#define SIMTEMP_SET_THRESHOLD _IOW(NXP_SIMTEMP_MAGIC, 3, __s32)
#define SIMTEMP_GET_SAMPLING _IOR(NXP_SIMTEMP_MAGIC, 4, __u32)

// FIX: Add the missing SIMTEMP_SET_SAMPLING macro
#define SIMTEMP_SET_SAMPLING _IOW(NXP_SIMTEMP_MAGIC, 5, __u32) 

#endif /* _NXP_SIMTEMP_IOCTL_H_ */